sudo: required
jdk:
- openjdk8
services:
- docker
branches:
  only:
  - master
env:
- NXF_ANSI_LOG=false
install:
- sudo apt-get -qq update
- sudo apt-get -qq -y install graphviz realpath
script:
- curl -fsSL get.nextflow.io | bash
- NXF_VER=20.07.1 ./nextflow run . -with-docker